### ISSUE TITLE
delete `do_padding()` call in workflow.R 

### ISSUE THREAD

**Issue by mrustl** [KWB-R/urbanAnnualRunoff#1]
Hi @RobertoTatisMuvdi, 

as you renamed the `do_padding()` function to `padCODE()` the following line should be deleted in `workflow.R`: 
https://github.com/KWB-R/urbanAnnualRunoff/blob/780f4f1451411fd6e7dd68728429669250f38567/workflow.R#L112

**Comment by ghost** [comment]
done!
