### ISSUE TITLE
Add workflow "jinxi" 

### ISSUE THREAD

**Issue by mrustl** [KWB-R/urbanAnnualRunoff#12]
based on workflow for Beijing

**Comment by mrustl** [comment]
Jinxi workflow is running but one error in ABIMO protocol:

```
Start der Berechnung am: 26.11.2020 um: 11:53:00

Bei der Berechnung traten 1 Fehler auf.

Bei 1 Flächen deren Wert 0 war wurde 100 eingesetzt.

Eingelesene Records: 287

Geschriebene Records: 287

Ende der Berechnung am: 26.11.2020 um: 11:53:00

```


[abimo.zip](https://github.com/KWB-R/urbanAnnualRunoff/files/5602429/abimo.zip)

**Comment by robetatis** [comment]
just finished adding and re-checking Jinxi workflow with no errors.
