### ISSUE TITLE
jinxi: check ABIMO error

### ISSUE THREAD

**Issue by mrustl** [KWB-R/urbanAnnualRunoff#16]
Jinxi workflow is running but one error in ABIMO protocol:

```
Start der Berechnung am: 26.11.2020 um: 11:53:00

Bei der Berechnung traten 1 Fehler auf.

Bei 1 Flächen deren Wert 0 war wurde 100 eingesetzt.

Eingelesene Records: 287

Geschriebene Records: 287

Ende der Berechnung am: 26.11.2020 um: 11:53:00

```

[abimo.zip](https://github.com/KWB-R/urbanAnnualRunoff/files/5602429/abimo.zip)

_Originally posted by @mrustl in https://github.com/KWB-R/urbanAnnualRunoff/issues/12#issuecomment-734229707_

**Comment by robetatis** [comment]
The error was not in R. The input data has a so-called 'sliver polygon', i.e., a very thin polygon with very small area. When we round to zero decimal places in line 248, this area becomes zero, and that's the error ABIMO is showing.
