### ISSUE TITLE
workflow.R: completley adapt to "bejing" use-case only

### ISSUE THREAD

**Issue by mrustl** [KWB-R/urbanAnnualRunoff#2]
https://github.com/KWB-R/urbanAnnualRunoff/blob/master/workflow.R contains paths to both "bejing" and "jinxi" use case, e.g.

https://github.com/KWB-R/urbanAnnualRunoff/blob/780f4f1451411fd6e7dd68728429669250f38567/workflow.R#L105
https://github.com/KWB-R/urbanAnnualRunoff/blob/780f4f1451411fd6e7dd68728429669250f38567/workflow.R#L178

To do: 
Adapt to "bejing" use-case only

**Comment by ghost** [comment]
done! I made the changes in a new branch 'beijing', which we can merge to master after checking.
