### ISSUE TITLE
invalid ABIMO input file created (prerequesites: 64-bit R, lots of RAM: > 16 GB ?)

### ISSUE THREAD

**Issue by mrustl** [KWB-R/urbanAnnualRunoff#5]
Hi @RobertoTatisMuvdi, 

Currently the ABIMO file created with the [workflow.R](https://github.com/KWB-R/urbanAnnualRunoff/blob/clean/workflow.R) from branch "clean" is invalid if I want to compute it with: 
`...\Data-Work packages\WP2_SUW_pollution_Beijing\_DataAnalysis\abimo\Abimo3.2\Abimo3.2.exe`

![grafik](https://user-images.githubusercontent.com/11964451/99263934-1f0de180-2820-11eb-8b25-d8d88a53a0b6.png)

Can you fix this by creating a new branch from "clean" (e.g. "fix-abimo") and provide your fixes there ?

**Comment by ghost** [comment]
Hi @mrustl 

I tried it on my machine and it runs (my local copy of the repo is up to date with the remote). 

Here's the ABIMO input file I generated:
[abimo_Beijing.zip](https://github.com/KWB-R/urbanAnnualRunoff/files/5548928/abimo_Beijing.zip)

If you want, send me your file and I'll check.

Cheers

Roberto

**Comment by mrustl** [comment]
My fault. R worfklow didn`t ran successuflly. First I had R 32bit open and got: 

```
> # compute ABIMO variable STR_FLGES (m2 street area)
> abimo@data$STR_FLGES <- makeSTR_FLGES(rawdir = paths$gis,
+                                       subcatchmSPobject = abimo,
+                                       mask = 'mask.shp',
+                                       rasterData = 'tzClass.tif',
+                                       overlayName = 'surfType',
+                                       targetValue = 2)

reading mask and raster data...
done

reading overlay object...
done

masking cells outside study area...Fehler: kann Vektor der Größe 608.4 MB nicht allozieren
Zusätzlich: Warnmeldungen:
1: In showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj = prefer_proj) :
  Discarded datum Unknown based on Krassovsky, 1942 ellipsoid in CRS definition
2: In OGRSpatialRef(dsn, layer, morphFromESRI = morphFromESRI, dumpSRS = dumpSRS,
```  

So these spatial operations take a lot of ram. Now I switched to 64-bit of R but now I im struggling with the machine learing training step in R with: 
https://github.com/KWB-R/urbanAnnualRunoff/blob/7cc203c3f2ee0b220c022336926dc4ab9faea240/workflow.R#L56 

```
loading spatial data...
done

extracting spectral signatures of ground truth areas...
done

saving overlay object...
done

training model...Fehler: kann Vektor der Größe 5.4 GB nicht allozieren
```

Can you pull the "clean" branch again and try to run the workflow R on your machine? Do you have more ram on your desktop computer at KWB?

**Comment by mrustl** [comment]
Solution for "beijing" -> use `groundtruth2.shp` (as it contains less training datasets and thus 16GB of RAM are sufficient). No issue for second case study "jinxi"
